# Generated by Django 4.2.7 on 2024-01-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='OrderItemID',
            new_name='OrderItem_ID',
        ),
    ]
