# Generated by Django 4.2.7 on 2023-12-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('OrderItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordApp.books')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordApp.orders')),
            ],
        ),
    ]
